name: CD

on:
  push:
    branches: ["main"]

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
  PLAYWRIGHT_URL: ${{ secrets.PLAYWRIGHT_URL }}

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: ${{env.working-directory}}/package-lock.json

      - name: Install Serverless
        run: npm i -g serverless
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: npm i
        working-directory: ${{env.working-directory}}

      - name: Deploy
        run: sls deploy --stage production
        working-directory: ${{env.working-directory}}

  e2e-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
