name: CD

on:
  push:
    branches: ["main"]

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    env:
      working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"
          cache-dependency-path: ${{env.working-directory}}/package-lock.json

      - name: Install Serverless
        run: npm i -g serverless
        working-directory: ${{env.working-directory}}

      - name: Install dependencies
        run: npm i
        working-directory: ${{env.working-directory}}

      - name: Deploy
        run: sls deploy --stage production
        working-directory: ${{env.working-directory}}
