name: CD

on:
  push:
    branches: [ "main" ]

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create package.json
        run: touch package.json && touch package-lock.json

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Initialise NPM
        run: npm init -y

      - name: Install Serverless
        run: npm i -g serverless

      - name: Build
        run: make

      - name: Deploy
        run: sls deploy --stage staging
