name: CD

on:
  pull_request:
  # push:
  #   branches: ["main"]

env:
  SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    working-directory: ./server
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install Serverless
        run: npm i -g serverless

      - name: Deploy
        run: sls deploy --stage staging
