name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Lint
        run: npm run lint
        working-directory: web
#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up Node
#        uses: actions/setup-node@v3
#        with:
#          node-version-file: '.nvmrc'
#
#      - name: Change working directory
#        run: cd server
#
#      - name: Test
#        run: npm run test
